BankSystemSolution/BankSystem.WebUI/Models/ExtendedSearchViewModel.cs
using System.Collections.Generic;
using BankSystem.Domain.Entities;

namespace BankSystem.WebUI.Models
{
    public class ExtendedSearchViewModel
    {
        public string DepositTypeName { get; set; }
        public IEnumerable<DepositType> DepositTypes { get; set; }
    }
}

BankSystemSolution/BankSystem.WebUI/Models/SearchViewModel.cs
using BankSystem.Domain.Entities;
using System.Collections.Generic;

namespace BankSystem.WebUI.Models
{
    public class SearchViewModel
    {      
        public IEnumerable<ApplicationUser> Depositors { get; set; }
        public IEnumerable<DepositType> DepositTypes { get; set; }
    }
}

BankSystemSolution/BankSystem.WebUI/Areas/Admin/Controllers/DepositController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using BankSystem.Domain.Entities;
using BankSystem.WebUI.Areas.Admin.Models;
using BankSystem.WebUI.Controllers;

namespace BankSystem.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DepositController : BankRepositoryController
    {
        public DepositController()
        {

        }
        // GET: Admin/Deposit
        public ActionResult Index()
        {
            var model = new DepositViewModel
            {
              Deposits = _repository.Deposits.ToList()
            };
            return View(model);
        }

        // GET: Admin/Deposit/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var deposit = _repository.Deposits.First(d => d.Id == id);

            if (deposit == null)
            {
                return HttpNotFound();
            }

            var model = new DepositViewModel {
                Id = deposit.Id,
                Interest = deposit.Interest,
                Money = deposit.Money,
                StartDate = deposit.StartDate,
                EndDate = deposit.EndDate,
                IsValid = deposit.IsValid
            }; 
            return View(model);
        }

        // GET: Admin/Deposit/Create
        public ActionResult Create()
        {
            DepositViewModel model = new DepositViewModel();

            //Initialization of SelectLists for DropDownLists
            ViewBag.BanksList = new SelectList(_repository.Banks.ToList().Where(b=>b.IsAble), nameof(Bank.Id), nameof(Bank.Name));
            ViewBag.DepositorsList = new SelectList(_repository.Depositors.ToList().Where(d=>d.IsBlocked == false), nameof(ApplicationUser.Id), nameof(ApplicationUser.UserName));
            ViewBag.DepositTypesList = new SelectList(_repository.DepositTypes.ToList(), nameof(DepositType.InterestRate), nameof(DepositType.Name));

            return View(model);
        }

        // POST: Admin/Deposit/Create         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "BankId,DepositorId,Interest,Money")] DepositViewModel model)
        {

            if (ModelState.IsValid)
            {
                var depo = new Deposit()
                {
                    Bank = _repository.Banks.First(b => b.Id == model.BankId),
                    Depositor = _repository.Depositors.First(d => d.Id == model.DepositorId),
                    Interest = _repository.DepositTypes.First(t => t.InterestRate == model.Interest).InterestRate,
                    Money = model.Money,
                    StartDate = DateTime.Now,
                    EndDate = DateTime.Now.AddDays(_repository.DepositTypes.First(t => t.InterestRate == model.Interest).PeriodInDays),
                    IsValid = true
                };
                _repository.Add(depo);

                await _repository.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            ViewBag.BanksList = new SelectList(_repository.Banks.ToList().Where(b => b.IsAble), nameof(Bank.Id), nameof(Bank.Name));
            ViewBag.DepositorsList = new SelectList(_repository.Depositors.ToList().Where(d => d.IsBlocked == false), nameof(ApplicationUser.Id), nameof(ApplicationUser.UserName));
            ViewBag.DepositTypesList = new SelectList(_repository.DepositTypes.ToList(), nameof(DepositType.InterestRate), nameof(DepositType.Name));

            return View(model);
        }   

        // GET: Admin/Deposit/Freeze/5
        public ActionResult Freeze(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var deposit = _repository.Deposits.First(d => d.Id == id);

            if (deposit == null)
            {
                return HttpNotFound();
            }

            var model = new DepositViewModel
            {
                Id = deposit.Id,
                Interest = deposit.Interest,
                Money = deposit.Money,
                StartDate = deposit.StartDate,
                EndDate = deposit.EndDate,
                IsValid = deposit.IsValid
            };

            return View(model);
        }

        // POST: Admin/Deposit/Freeze/5
        [HttpPost, ActionName("Freeze")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> FreezeConfirmed(int id)
        {
            var deposit = _repository.Deposits.First(d => d.Id == id);

            if (deposit != null)
            {
                deposit.IsValid = false;
                await _repository.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        // GET: Admin/Deposit/Reinstate/5
        public ActionResult Reinstate(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Deposit deposit = _repository.Deposits.First(d => d.Id == id);

            if (deposit == null)
            {
                return HttpNotFound();
            }

            var model = new DepositViewModel
            {
                Id = deposit.Id,
                Interest = deposit.Interest,
                Money = deposit.Money,
                StartDate = deposit.StartDate,
                EndDate = deposit.EndDate,
                IsValid = deposit.IsValid
            };

            return View(model);
        }

        // POST: Admin/Deposit/Reinstate/5
        [HttpPost, ActionName("Reinstate")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ReinstateConfirmed(int id)
        {
            var deposit = _repository.Deposits.First(d => d.Id == id);

            if (deposit != null && deposit.IsValid ==false)
            {
                deposit.IsValid = true;
                await _repository.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

    }
}

BankSystemSolution/BankSystem.WebUI/Controllers/ExtendedSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BankSystem.Domain.Entities;
using BankSystem.WebUI.Models;

namespace BankSystem.WebUI.Controllers
{
    public class ExtendedSearchController : BankRepositoryController
    {
        // GET: ExtendedSearch
        public ActionResult Index()
        {
            ViewBag.DepositTypesList = new SelectList(_repository.DepositTypes.ToList(), nameof(DepositType.Name), nameof(DepositType.Name));
            return View();
        }

        public PartialViewResult ExtendedSearchPartial(string bank = "", string depositor = "", string depositTypeName = "",
            string minAmount = "", string maxAmount = "",
            string firstDate = "", string lastDate = "")
        {

            //CheckForEmptyInputs
            firstDate = firstDate == "" ? DateTime.MinValue.ToString() : firstDate;
            lastDate = lastDate == "" ? DateTime.MaxValue.ToString() : lastDate;
            minAmount = minAmount == "" ? "0" : minAmount;
            maxAmount = maxAmount == "" ? decimal.MaxValue.ToString() : maxAmount;

            bank = bank.ToLower();
            depositor = depositor.ToLower();
            decimal dMinAmount = Convert.ToDecimal(minAmount);
            decimal dMaxAmount = Convert.ToDecimal(maxAmount);
            DateTime dFirstDate = Convert.ToDateTime(firstDate);
            DateTime dLastDate = Convert.ToDateTime(lastDate);
            ViewBag.DepositTypesList = new SelectList(_repository.DepositTypes.ToList(), nameof(DepositType.Name), nameof(DepositType.Name));

            var model = new SearchViewModel
            {
                DepositTypes = _repository.DepositTypes.ToList(),

                Depositors = _repository.Deposits.ToList()
                    .Where(d => d.Bank.Name.ToLower().Contains(bank) &&  //Bank
                                d.Depositor.FullName.ToLower().Contains(depositor) && //Depositor
                                d.Interest == _repository.DepositTypes.First(t => t.Name.Contains(depositTypeName)).InterestRate && //DepositType
                                d.Money > dMinAmount && d.Money < dMaxAmount && // Amount
                                d.StartDate > dFirstDate && d.StartDate < dLastDate) //Date
                    .Select(d => d.Depositor)
                    .Distinct()
                    .ToList()
            };

            return PartialView("ExtendedSearchPartial", model);
        }
    }
}

BankSystemSolution/BankSystem.WebUI/Controllers/HomeController.cs
using BankSystem.Domain.Entities;
using BankSystem.WebUI.Models;
using System;
using System.Globalization;
using System.Text;
using System.Linq;
using System.Web.Mvc;

namespace BankSystem.WebUI.Controllers
{
    public class HomeController : BankRepositoryController
    {
        public HomeController()
        {

        }
        //
        //Home Page
        public ActionResult Index()
        {
            ViewBag.DepositTypesList = new SelectList(_repository.DepositTypes.ToList(), nameof(DepositType.Name), nameof(DepositType.Name));

            var model = new HomePageViewModel
            {
                DepositTypes = _repository.DepositTypes.ToList(),
                Banks = _repository.Banks.Where(b => b.IsAble).ToList(),
                Depositors = _repository.Depositors.ToList()
            };

            return View(model);
        }

        public ActionResult Search(string searchBy, string searchString = "0", string depositTypeName = "", string minValue = "0", string maxValue = "0")
        {
            ViewBag.SearchBy = searchBy;
            ViewBag.SearchString = searchString;
            ViewBag.DepositTypeName = depositTypeName;
            ViewBag.MinVal = minValue;
            ViewBag.MaxVal = maxValue;
            ViewBag.DepositTypesList = new SelectList(_repository.DepositTypes.ToList(), nameof(DepositType.Name), nameof(DepositType.Name));

            var searchStr = searchString.ToLower();

            var model = new SearchViewModel()
            {
                DepositTypes = _repository.DepositTypes.ToList(),
                Depositors = _repository.Depositors.ToList()
            };

            switch (searchBy)
            {
                case "Bank":
                    model.Depositors = _repository.Deposits.ToList()
                        .Where(d => d.Bank.Name.ToLower().Contains(searchStr))
                        .Select(d => d.Depositor)
                        .Distinct().ToList();
                    return View(model);

                case "Depositor":
                    model.Depositors = _repository.Depositors
                        .Where(d => d.FullName.ToLower().Contains(searchStr))
                        .ToList();
                    return View(model);

                case "Deposit Type":
                    model.Depositors = _repository.Deposits.ToList()
                        .Where(d => d.Interest == _repository.DepositTypes.First(t => t.Name.Contains(depositTypeName)).InterestRate)
                        .Select(d => d.Depositor)
                        .Distinct().ToList();
                    return View(model);

                case "Amount":
                    decimal dMinAmount = Convert.ToDecimal(minValue);
                    decimal dMaxAmount = Convert.ToDecimal(maxValue);

                    model.Depositors = _repository.Deposits.ToList()
                        .Where(d => d.Money > dMinAmount && d.Money < dMaxAmount)
                        .Select(d => d.Depositor)
                        .Distinct().ToList();
                    return View(model);

                case "Date":
                    DateTime dFirstDate = Convert.ToDateTime(minValue);
                    DateTime dLastDate = Convert.ToDateTime(maxValue);

                    model.Depositors = _repository.Deposits.ToList()
                        .Where(d => d.StartDate > dFirstDate && d.StartDate < dLastDate)
                        .Select(d => d.Depositor)
                        .Distinct().ToList();
                    return View(model);

                default:
                    return View(model);

            }
        }
    }
}

BankSystemSolution/BankSystem.WebUI/Views/Home/ExtendedSearch.cshtml
@model BankSystem.WebUI.Models.ExtendedSearchViewModel
@{
    ViewBag.Title = "ExtendedSearch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ExtendedSearch</h2>
<hr />
<div class="container ex-search">
    <div class="row">
        <div class="col-xs-12">
            @using (Ajax.BeginForm("ExtendedSearchPartial", "Home", new { area = "" },
                new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "exSearchResult",
                    LoadingElementId ="loading" }))
            {
                <div class="col-xs-4">
                    <input type="search" name="bank" value="" placeholder="Bank..." id="bank" class="form-control inline-block "  />
                    <input type="search" name="depositor" value="" placeholder="Depositor..." id="depositor" class="form-control inline-block "  />
                    @Html.DropDownListFor(m => m.DepositTypeName, ViewBag.DepositTypesList as IEnumerable<SelectListItem>, "Select Interest",new{@class= "form-control inline-block" })
                </div>
                <div class="col-xs-4">
                    <label>Amount</label>
                    <input type="number" name="minAmount" value="" placeholder="from" id="minAmount"  class="form-control inline-block " />
                    <input type="number" name="maxAmount" value="" placeholder="to" id="maxAmount"  class="form-control inline-block " />

                </div>
                <div class="col-xs-4">
                    <label>Date</label>
                    <input type="date" name="firstDate" value="" placeholder="yyyy/mm/dd" id="firstDate" pattern="\d{4}-\d{1,2}-\d{1,2}" class="form-control inline-block "  />
                    <input type="date" name="lastDate" value="" placeholder="yyyy/mm/dd" id="lastDate" pattern="\d{4}-\d{1,2}-\d{1,2}" class="form-control inline-block " />
                </div>
                <input type="submit" value="Find" class="btn btn-success" />
            }
        </div>
    </div>
</div>

<div id="exSearchResult" style="margin-top:100px;"></div>

<div id="loading" style="display:none"> </div>

<script>
    $(function () {
        $("#firstDate, #lastDate").datepicker({
            dateFormat: "yy-mm-dd"
        });
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankSystemSolution/BankSystem.WebUI/Views/Home/ExtendedSearchPartial.cshtml
@model BankSystem.WebUI.Models.SearchViewModel

@if (!Model.Depositors.Any())
{
    <div class="col-md-11 col-md-offset-1 search-item">
        <div class="row">
            <div class="col-md-12">
                <h3> 0 Results</h3>
            </div>
        </div>
    </div>
}

else
{
    <div class="col-md-11 col-md-offset-1 search-item">
        <div class="row">
            <div class="col-md-12">
                <h3> @Model.Depositors.Count() Results</h3>
            </div>
        </div>
    </div>

    foreach (var item in Model.Depositors.Where(d => d.Deposits.Any()))
    {
        <div class="col-md-11 col-md-offset-1 search-item">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-6 glyphicon glyphicon-user search-item-img"></div>
                        <div class="col-md-6">
                            <p></p>
                            <h2>@item.Name @item.Surname</h2>
                            <strong>Phone:</strong> @item.PhoneNumber
                            <p><strong>Email:</strong> <a href="http://@item.Email">@item.Email</a>
                            </p>
                        </div>
                        <div class="col-md-12 search-item-deposits">
                            <h3>Deposits</h3>
                            @foreach (var i in item.Deposits)
                            {
                                <pre><a href="http://@i.Bank.WebSite" target="_blank">@i.Bank.Name</a> <strong> @Model.DepositTypes.First(t => t.InterestRate == i.Interest).Name (@i.Interest %)  </strong></pre>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}

BankSystemSolution/BankSystem.WebUI/Views/Home/Index.cshtml
@model BankSystem.WebUI.Models.HomePageViewModel
@{

    ViewBag.Title = "Trust Deposit | Make Your Dreams Come True With Us!";
}

<article>
    <section class="page-head">
        <div class="container">
            <div class="row">
                <div class="col-lg-12"><h1> We Will Take <strong>CARE</strong> About Your Money </h1></div>
            </div>
            <div class="row">
                <div class="col-xs-3 ">
                    <img src="~/Content/Images/bank-icon.png" alt="" />
                </div>
                <div class="col-xs-3">
                    <img src="~/Content/Images/wallet-flat.png" alt="" />
                </div>
                <div class="col-xs-3">
                    <img src="~/Content/Images/calendar-icon.png" alt="" />
                </div>
                <div class="col-xs-3">
                    <img src="~/Content/Images/money_bag.png" alt="" />
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3"> Find the bank of your dreams</div>
                <div class="col-xs-3"> Trust your money to us</div>
                <div class="col-xs-3 "> Be patient</div>
                <div class="col-xs-3"> Earn money you needed for happiness</div>
            </div>
            <div class="row">
                <a href="@Url.Action("Create","Deposit")" class="deposit-btn top-deposit-btn">Deposit Now</a>
            </div>
        </div>
    </section>

    <div class="search-div">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <p> Already @Model.Depositors.Count() Depositors trust us</p>
                    @using (Html.BeginForm("Search", "Home", FormMethod.Get))
                    {
                        <input type="search" name="searchString" value="" placeholder="Search..." id="searchStr" class="" required />
                        <input type="search" name="minValue" value="" placeholder="Starts" id="minval" class="hidden" />
                        <input type="search" name="maxValue" value="" placeholder="Ends" id="maxval" class="hidden" />
                        @Html.DropDownListFor(m => m.DepositTypeName, ViewBag.DepositTypesList as IEnumerable<SelectListItem>, "Select Interest", new { @class = " hidden" })
                        @Html.ValidationMessageFor(model => model.DepositTypeName, "", new { @class = "text-danger" })
                        <span>By</span>
                        <select id="searchFilter" name="searchBy">
                            <option selected>Bank</option>
                            <option>Deposit Type</option>
                            <option>Depositor</option>
                            <option>Amount</option>
                            <option>Date</option>
                        </select>
                        <input type="submit" name="name" value="Find" />

                    }
                </div>
                <a href="@Url.Action("Index","ExtendedSearch", new {  area = ""})" class="btn">Extended Search</a>
                <h4>Our dept to provide full information <br> needed for our clients to grow thair money in safe.</h4>
            </div>
        </div>
    </div>

    <section class="banks" id="Banks_id">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h1 class="big-bold-center underlined"> &nbsp;Banks&nbsp;</h1>
                    <h4 style="color:#fff">Choose the Bank where you want to Deposit</h4>
                </div>
            </div>
            <div class="container">
                <div class="row">

                    @foreach (var item in Model.Banks)
                    {
                        <div class="col-md-4">
                            <div class="bank-item " onclick="new function() { $('#bankinfo-@{@item.Id}').toggleClass('hidden'); $('#bankitemimg-@{@item.Id}').toggleClass('hidden'); }">
                                <p id="bankinfo-@item.Id" class="hidden" style="margin:0 auto; font-size:18px; font-weight:bold;">
                                    @item.Name<br />
                                    @item.Address<br />
                                    @item.Email <br />
                                    @item.PhoneNumber <br />

                                    <a href="http://@item.WebSite" target="_blank">http://www.@item.WebSite </a><br />
                                    <a href="@Url.Action("Create","Deposit", new {  area = ""})?bankId=@item.Id">Deposit Now</a>
                                </p>
                                <br />
                                <img src="@item.ImageUrl" id="bankitemimg-@item.Id" alt="" />
                            </div>
                        </div>
    }
                </div>
            </div>
        </div>
    </section>

    <section class="bestoffers" id="Offers_id">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="col-xs-12 big-bold-center ">
                        <h1 class="big-bold-center underlined">&nbsp;Best Offers&nbsp;</h1>
                        <h4 style="color:#fff">Here they are! The best conditions for your money</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 ">
                    @foreach (var item in Model.DepositTypes)
                    {
                        <div class=" row offer-item">
                            <div class="col-xs-12">
                                <img src="@item.ImageUrl" alt="" />
                            </div>
                            <div class="col-xs-12"> <p>@item.Name</p></div>
                            <div class="col-xs-12"> <p><strong>@item.InterestRate%</strong></p></div>
                            <div class="col-xs-12">
                                <ul>
                                    <li>Period: @item.PeriodInDays days</li>
                                </ul>
                            </div>
                            <div class="col-xs-12"> <a href="@Url.Action("Create", "Deposit", new { area = ""})?interest=@item.InterestRate" class="deposit-btn @item.Name-btn">Deposit</a></div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

    <section id="WhyUs_id" class="AboutUs">
        <div class="container">
            <div class="row">
                <div class="col-xs-12"><h1 class="big-bold-center"> &nbsp;Why Us?&nbsp;</h1> </div>
                <div class="col-xs-12">
                    <p class="text-center">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Aenean orci magna, accumsan sit amet mi a, vestibulum convallis ex.
                        Nunc laoreet tincidunt nibh, vitae efficitur diam mattis vel. Fusce nec magna eu ex efficitur maximus.
                        Curabitur egestas metus id massa consectetur, eget molestie mauris tempor. Duis feugiat vehicula auctor.
                        Nunc imperdiet dignissim pellentesque. Vivamus ut mi et eros aliquam fringilla.
                        Ut dignissim metus et felis facilisis, nec fermentum eros congue. Donec accumsan fringilla tortor,
                        non luctus diam consequat eget. Proin eget massa placerat, consequat dui pharetra, aliquet lectus.
                    </p>
                </div>
                <div class="col-xs-12"></div>
            </div>
        </div>
    </section>
</article>
<script>
    $('#searchFilter').change(changeSearchInputs);
    $('#searchFilter').ready(changeSearchInputs);

</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankSystemSolution/BankSystem.WebUI/Views/Home/Search.cshtml
@model  BankSystem.WebUI.Models.SearchViewModel
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@if (ViewBag.SearchBy == "Amount" || ViewBag.SearchBy == "Date")
{
    
    <h2>@Model.Depositors.Count() Results for searching by @ViewBag.SearchBy. Range: @ViewBag.MinVal - @ViewBag.MaxVal</h2>
}
else
{
<h2>@Model.Depositors.Count(d => d.Deposits.Any()) Results for searching <strong>"@ViewBag.SearchString @ViewBag.DepositTypeName"</strong> by @ViewBag.SearchBy </h2>
}
<hr />
<a href="@Url.Action("Index","ExtendedSearch", new {  area = ""})?" class="btn">Extended Search</a>
<hr />
@foreach (var item in Model.Depositors.Where(d=>d.Deposits.Any()))
{ 
    <div class="col-md-11 col-md-offset-1 search-item">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6 glyphicon glyphicon-user search-item-img"></div>
                    <div class="col-md-6">
                        <p></p>
                        <h2>@item.Name @item.Surname</h2>
                        <strong>Phone:</strong> @item.PhoneNumber
                        <p><strong>Email:</strong> <a href="http://@item.Email">@item.Email</a></p>
                    </div>
                    <div class="col-md-12 search-item-deposits">
                        <h3>Deposits</h3>
                        @foreach (var i in item.Deposits)
                        {
                            <pre><a href="http://@i.Bank.WebSite" target="_blank">@i.Bank.Name</a> <strong> @Model.DepositTypes.First(t=>t.InterestRate == i.Interest).Name (@i.Interest %)  </strong></pre>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}