BankSystemSolution/BankSystem.WebUI/Areas/Admin/Models/BankViewModel.cs
using BankSystem.Domain.Entities;
using System.Collections.Generic;

namespace BankSystem.WebUI.Areas.Admin.Models
{
    public class BankViewModel
    {
        public int Id { get; set; }
       
        public string Name { get; set; }
        
        public string Address { get; set; }
       
        public string PhoneNumber { get; set; }
       
        public string Email { get; set; }

        public string ImageUrl { get; set; }

        public string WebSite { get; set; }

        public bool IsAble { get; set; }

        public IEnumerable<Bank> Banks{ get; set; }
        public IEnumerable<Deposit> Deposits { get; set; }

    }
}

BankSystemSolution/BankSystem.WebUI/Areas/Admin/Controllers/BankController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using BankSystem.Domain.Entities;
using BankSystem.WebUI.Controllers;
using BankSystem.WebUI.Areas.Admin.Models;

namespace BankSystem.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BankController : BankRepositoryController
    {
        public BankController()
        {

        }
       
        public ActionResult Index()
        {
            var model = new BankViewModel {
                Banks = _repository.Banks.ToList()
            };
            return View(model);
        }

        // GET: Bank/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var bank = _repository.Banks.First(b => b.Id == id);     
            
            if (bank == null)
            {
                return HttpNotFound();
            }

            var model = new BankViewModel {
                Id = bank.Id,
                Name = bank.Name,
                Address = bank.Address,
                PhoneNumber = bank.PhoneNumber,
                Email = bank.Email,
                ImageUrl = bank.ImageUrl,
                WebSite = bank.WebSite,
                IsAble = bank.IsAble
            };
            return View(model);
        }

        // GET: Bank/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bank/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Address,PhoneNumber,Email,ImageUrl,WebSite")] BankViewModel model)
        {
            if (ModelState.IsValid)
            {
                var bank = new Bank
                {
                    Id = model.Id,
                    Name = model.Name,
                    Address = model.Address,
                    PhoneNumber = model.PhoneNumber,
                    Email = model.Email,
                    ImageUrl = model.ImageUrl,
                    WebSite = model.WebSite,
                    IsAble = true
                };               
                _repository.Add(bank);
                await _repository.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Bank/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var bank = _repository.Banks.First(b => b.Id == id);

            if (bank == null)
            {
                return HttpNotFound();
            }

            var model = new BankViewModel
            {
                Id = bank.Id,
                Name = bank.Name,
                Address = bank.Address,
                PhoneNumber = bank.PhoneNumber,
                Email = bank.Email,
                ImageUrl = bank.ImageUrl,
                WebSite = bank.WebSite,
                IsAble = bank.IsAble
            };
            return View(model);
        }

        // POST: Bank/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Address,PhoneNumber,Email,ImageUrl,WebSite,IsAble")] BankViewModel model)
        {
            if (ModelState.IsValid)
            {
                Bank bank = new Bank
                {
                    Id = model.Id,
                    Name = model.Name,
                    Address = model.Address,
                    PhoneNumber= model.PhoneNumber,
                    Email= model.Email,
                    ImageUrl = model.ImageUrl,
                    WebSite = model.WebSite,
                    IsAble = model.IsAble
                };
                _repository.Entry(bank).State = EntityState.Modified;

                await _repository.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Bank/Disable/5
        public ActionResult Disable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Bank bank = _repository.Banks.First(b => b.Id == id);
            if (bank == null)
            {
                return HttpNotFound();
            }
            var model = new BankViewModel
            {
                Id = bank.Id,
                Name = bank.Name,
                Address = bank.Address,
                PhoneNumber = bank.PhoneNumber,
                Email = bank.Email,
                ImageUrl = bank.ImageUrl,
                WebSite = bank.WebSite,
                IsAble = bank.IsAble
            };
            return View(model);
        }

        // POST: Bank/Disable/5
        [HttpPost, ActionName("Disable")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DisableConfirmed(int id)
        {
            Bank bank = _repository.Banks.First(b => b.Id == id);

            if (bank != null)
            {
                bank.IsAble = false;
                await _repository.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        // GET: Bank/Reinstate/5
        public ActionResult Reinstate(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Bank bank = _repository.Banks.First(b => b.Id == id);
            if (bank == null)
            {
                return HttpNotFound();
            }
            var model = new BankViewModel
            {
                Id = bank.Id,
                Name = bank.Name,
                Address = bank.Address,
                PhoneNumber = bank.PhoneNumber,
                Email = bank.Email,
                ImageUrl = bank.ImageUrl,
                WebSite = bank.WebSite,
                IsAble = bank.IsAble
            };
            return View(model);
        }

        // POST: Bank/Disable/5
        [HttpPost, ActionName("Reinstate")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ReinstateConfirmed(int id)
        {
            Bank bank = _repository.Banks.First(b => b.Id == id);

            if (bank != null && bank.IsAble == false)
            {
                bank.IsAble = true;
                await _repository.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        // GET: Bank/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Bank bank = _repository.Banks.First(b => b.Id == id);

            if (bank == null)
            {
                return HttpNotFound();
            }

            var model = new BankViewModel
            {
                Id = bank.Id,
                Name = bank.Name,
                Address = bank.Address,
                PhoneNumber = bank.PhoneNumber,
                Email = bank.Email,
                ImageUrl = bank.ImageUrl,
                WebSite = bank.WebSite,
                IsAble = bank.IsAble,
                Deposits = bank.Deposits
            };
            return View(model);
        }

        // POST: Bank/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            _repository.Remove<Bank>(id);
            await _repository.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

BankSystemSolution/BankSystem.WebUI/Areas/Admin/Views/Bank/Create.cshtml
@model BankSystem.WebUI.Areas.Admin.Models.BankViewModel

@{
    ViewBag.Title = "Creating Bank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <h2>Create</h2>


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Bank</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.WebSite, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.WebSite, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.WebSite, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
            <hr />
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankSystemSolution/BankSystem.WebUI/Areas/Admin/Views/Bank/Delete.cshtml
@model BankSystem.WebUI.Areas.Admin.Models.BankViewModel

@{
    ViewBag.Title = "Delete Bank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        @if (Model.Deposits.Count() > 0)
        {
            <h3>You Can Not Delete Bank, which have Deposits</h3>
           
            @Html.ActionLink("Go Back","Index", "Bank", new { area = "Admin"}, new {@class = "btn btn-success"});
            <hr />
            <h3> But you can still Disable It </h3>
            @Html.ActionLink("Disable", "Disable", "Bank", new { area = "Admin", id = Model.Id }, new { @class = "btn btn-danger" });

        }
        else
        {
        <div class="col-md-12">

            <h2>Delete</h2>

            <h3>Are you sure you want to Delete this Bank?</h3>
            <div>                
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ImageUrl)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ImageUrl)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.WebSite)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.WebSite)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                    <hr />
                }

            </div>
        </div>
        }
    </div>
</div>

BankSystemSolution/BankSystem.WebUI/Areas/Admin/Views/Bank/Details.cshtml
@model BankSystem.WebUI.Areas.Admin.Models.BankViewModel

@{
    ViewBag.Title = "Bank Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <h2>Details</h2>

            <div>
                <h4>Bank</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ImageUrl)
                    </dt>
                    
                    <dd>
                        <img src="@Model.ImageUrl" alt="@Model.Name" style="background-color:#fff; padding: 10px; border-radius: 5px;" />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.WebSite)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.WebSite)
                    </dd>

                </dl>
            </div>
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
                @Html.ActionLink("Back to List", "Index")
            </p>
            <hr />
        </div>
    </div>
</div>

BankSystemSolution/BankSystem.WebUI/Areas/Admin/Views/Bank/Disable.cshtml
@model BankSystem.WebUI.Areas.Admin.Models.BankViewModel

@{
    ViewBag.Title = "Delete Bank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <h2>Disable</h2>

            <h3>Are you sure you want to Disable this Bank?</h3>
            <div>                
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Disable" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                    <hr />
                }

            </div>
        </div>
    </div>
</div>

BankSystemSolution/BankSystem.WebUI/Areas/Admin/Views/Bank/Edit.cshtml
@model BankSystem.WebUI.Areas.Admin.Models.BankViewModel
@{
    ViewBag.Title = "Edit Bank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <h2>Edit</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Bank</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.WebSite, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.WebSite, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.WebSite, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.IsAble, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.IsAble)
                            @Html.ValidationMessageFor(model => model.IsAble, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
            <hr />
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankSystemSolution/BankSystem.WebUI/Areas/Admin/Views/Bank/Index.cshtml
@model BankSystem.WebUI.Areas.Admin.Models.BankViewModel

@{
    ViewBag.Title = "Banks Manage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <h2>Banks Manager</h2>

            <p>
                @Html.ActionLink("Create New", "Create")
            </p>

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.IsAble)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Address)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ImageUrl)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WebSite)
                    </th>
                    
                    <th></th>
                </tr>

                @foreach (var item in Model.Banks)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsAble)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            <img  style="max-width:100px;"  src="@item.ImageUrl"  alt="@item.ImageUrl"/>
                            @*@Html.DisplayFor(modelItem => item.ImageUrl)*@
                        </td>
                        <td>
                            <a href="http://@item.WebSite" target="_blank">@Html.DisplayFor(modelItem => item.WebSite)</a>
                        </td>
                        <td style=" background-color:#eeeeee;">
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                            @if (item.IsAble == true){@Html.ActionLink("Disable", "Disable", new { id = item.Id }) }
                            else {@Html.ActionLink("Reinstate", "Reinstate", new { id = item.Id }) } |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                        </td>
                        
                    </tr>
                }

            </table>
            <hr />
        </div>
    </div>
</div>

BankSystemSolution/BankSystem.WebUI/Areas/Admin/Views/Bank/Reinstate.cshtml
@model BankSystem.WebUI.Areas.Admin.Models.BankViewModel

@{
    ViewBag.Title = "Reinstate Bank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <h2>Reinstate</h2>

            <h3>Are you sure you want to Reinstate this Bank?</h3>
            <div>                
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Reinstate" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                    <hr />
                }

            </div>
        </div>
    </div>
</div>